# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Khitwa
email: eng.mihyear@gmail.com
description: A Step in the right direction
baseurl: "" # the subpath of your site, e.g. /blog
url: "mihyar-30614.github.io" # the base hostname & protocol for your site
twitter_username: MihyarMas
github_username:  mihyar-30614

# Build settings
markdown: kramdown
